### ISSUE TITLE
Can't use a function custom formatter

### ISSUE THREAD

**Issue by Starwort** [s-cork/Tabulator#1]
While it's possible to pass a component as a custom formatter, it is not possible to pass a function as a custom formatter, as implied [in the tabulator wiki](http://tabulator.info/docs/4.7/format#format-custom); I realise this could be hard to implement, however it would be rather useful! (perhaps, if not fully custom formatters, you could add a datetime object formatter?)

> # Custom Formatters
> As well as the built-in formatters you can define a formatter using a custom formatter function.
> 
> The formatter function accepts two arguments, the CellComponent for the cell being formatted and the formatterParams option from the column definition.
> 
> The function must return the contents of the cell, either the text value of the cell, valid HTML or a DOM node.
> 
> ```js
> {title:"Name", field:"name", formatter:function(cell, formatterParams, onRendered){
>     //cell - the cell component
>     //formatterParams - parameters set for the column
>     //onRendered - function to call when the formatter has been rendered
> 
>     return "Mr" + cell.getValue(); //return the contents of the cell;
> },
> }
> ```

**Comment by s-cork** [comment]
It should be possible. I've written lots of function based formatters. 

The formatted should accept an arg row and optional parameters. Eg

```python
..., 'formatter': self.icon_cell...}]


def icon_cell(self, row, **params):
    return Button(text=row['some_field'])

```

I can provide further examples and a clone if necessary. 

I also have an example on the anvil forum with a more involved example. 

https://anvil.works/forum/t/tabulator-with-anvil-components/4646/6

**Comment by Starwort** [comment]
My request was more about having it return a string like the normal custom formatters; having one of my components as a Label makes it aligned differently to the rest of the table (and I prefer the compactness of the default text formatting); perhaps a flag could be used in formatterParams to specify to Tabulator that it's returning a string instead of a component?

**Comment by s-cork** [comment]
Have your tried using a label component where the role is text and the spacing above and below is set to none.

**Comment by Starwort** [comment]
I tried, it's considerably lower for seemingly little reason. If this is possible that'd be amazing though!

**Comment by Starwort** [comment]
While we're at it do you think you can come up with [custom sorters](http://tabulator.info/docs/4.0/sort#func-custom) too?
> ```js
> {title:"Name", field:"name", sorter:function(a, b, aRow, bRow, column, dir, sorterParams){
>         //a, b - the two values being compared
>         //aRow, bRow - the row components for the values being compared (useful if you need to access additional fields in the row data for the sort)
>         //column - the column component for the column being sorted
>         //dir - the direction of the sort ("asc" or "desc")
>         //sorterParams - sorterParams object from column definition array
> 
>         return a - b; //you must return the difference between the two values
>     },
> }
> ```

**Comment by s-cork** [comment]
Yeah. That should be fine. Just an extension of the other functions based approaches. What's the use case for the custom sorter?

I think I'd make the call signature such that a, b were required args and then the rest were keyword args. 

So all the following functions would work as valid call signatures 

```python
def f(a, b, aRow, bRow, **params):

def f(a,b,**params):

def f(self, a, b, aRow, bRow, **params):

def f(self, a, b, **params):

```

**Comment by Starwort** [comment]
> What's the use case for the custom sorter?
Same as the use case for the custom formatter lol

I want to use datetime objects in my table without having to deal with converting them to/from javascript every time I want to edit/save them

That's certainly an interesting way of handling it, although `def f(a, b, *)` should be able to drop positional args that aren't used.

Your method certainly looks more like default anvil, though.

**Comment by s-cork** [comment]
i've implemented the str as formatter and moved custom sorter to a new issue

**Comment by Starwort** [comment]
> The function must return the contents of the cell, either the text value of the cell, **valid HTML or a DOM node**.

So I just found out that you can't return HTML, which is a bit of a shame but not the highest priority; if this isn't too difficult to implement do you think you could? Thanks in advance :)

**Comment by s-cork** [comment]
Example? Currently you can write python to pass a function that returns an anvil component or text... or just pass an anvil component directly.

**Comment by s-cork** [comment]
I've done some little experiments and I think returning a string of valid html works no problem...
```python
{'title':"foo", 'formatter': lambda row: "<button class='btn'><span>'foo'</span></button>"...
```

**Comment by Starwort** [comment]
I returned an `f'<a href="[...]{row["name"]}">{row["name"]}</a>'` and it didn't render anything in the field, after inspecting the cell there was absolutely nothing there; changing the `<`s to `&lt;`s made it render the HTML string; I set it back to an anvil component for now but it looks kinda out of place; perhaps I missed an extra commit that makes HTML work lol

**Comment by Starwort** [comment]
My exact code is
```py
...
    # Any code you write here will run when the form opens.
    def generate_url(row, **params):
        return f'<a href="https://acnh-fossils.anvil.app/#users/{row["name"]}>{row["name"]}</a>'
    self.results.columns = [
            {"title": "User's name", "field": "name", 'formatter': UsernameFormatter},
#             {"title": "User's name", "field": "name", 'formatter': generate_url},
            {"title": "User information", "field": "bio"},
...
```

**Comment by s-cork** [comment]
It doesn't look like you've closed the first a tag `"></a>`

**Comment by Starwort** [comment]
Good spot! Thanks lol
