### ISSUE TITLE
Easy way to set background or cell color depending on a cell value 

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#10]
Hi Stu

I could not find a simple way to have the background color of a cell change on the value of cell, while still displaying the string value as well. I guess if I only want to change BG color I could use the 'color' formatter. 

Currently I use this method, which seems a bit clumsy:
```
    def status_formatter(row):
      COLORS = {'IN': 'green', 'UIT': 'red', 'THUIS': 'orange'}
      color = COLORS.get(row['status'], 'gray') 
      return f"<div style='width: 100px; height: 30px; text-align: center; background-color: {color};'>{row['status']}</div>"
    
    columns = [
      {'title':"Naam", 'field':"name"},
      {'title':"Status", 
       'field':"status", 
       'formatter': status_formatter,
        'width': 100,},
```
I could also envision coloring the whole row based on a cell's value. 

TIA

**Comment by s-cork** [comment]
I think you'd definitely need the formatter.
The tabulator way to do this would be to do something like

```python
    def status_formatter(row, cell):
      COLORS = {'IN': 'green', 'UIT': 'red', 'THUIS': 'orange'}
      color = COLORS.get(row['status'], 'gray')
      cell.getElement().style.backgroundColor = color #cell is a tabulator object
      return row['status']
    
    columns = [
      {'title':"Naam", 'field':"name"},
      {'title':"Status", 
       'field':"status", 
       'formatter': status_formatter,
        'width': 100,},
```

But i'm not convinced that's much better...

Thoughts?

**Comment by mjmare** [comment]
I'd say it is a tad more tabulatoresque (making it a bit easier to use the T documentation). However, it does not work since the formatter has only 1 arg: row; it is missing the cell arg. 
Having a cell reference would be useful to have. 
Would be even nicer to have it as a python object. Something like: cell.element.style.background_color. But that would mean a lot of wrapping classes probably.

**Comment by s-cork** [comment]
Snake case would be nice but that's a lot of wrapping.

I'm happy to consider changing the api and including the cell as an extra argument.

I'm also happy to change the first argument to be the cell if it might be better. 

Either way it's a breaking change so would need to update the examples.

**Comment by mjmare** [comment]
Lot of wrapping is a lot of work and a lot of maintenance; not worth it. 

Might it be worth it to wrap the row object (instead of a dict). If it behaves like dict it won't be a breaking change, yet it might expose interesting methods to get the tabulator cell(s).

If you do make a breaking change, maybe adhere to the original Tabulator args, followed by any extra args.

**Comment by s-cork** [comment]
The row object is different to the row data. Exposing the row object would be a breaking change since you'd have to call `getData` on that object.

As an alternative I could add an api `cellFormatter` and this could be the tabulator version with tabulator arguments.
```python
    def status_formatter(cell, formatterParams, onRendered):
      COLORS = {'IN': 'green', 'UIT': 'red', 'THUIS': 'orange'}
      status = cell.getValue()
      color = COLORS[status]
      cell.getElement().style.backgroundColor = color
      return status
    
    columns = [
      {'title':"Naam", 'field':"name"},
      {'title':"Status", 
       'field':"status", 
       'cellFormatter': status_formatter,
        'width': 100,},
```

I think that might be the way to go - it's a 3 line change.

**Comment by mjmare** [comment]
That's a nice solution. 

Maybe add a rowFormatter at the same time? 

Thanks for the prompt responses BTW!

**Comment by s-cork** [comment]
I think you can already use the rowFormatter http://tabulator.info/docs/4.9/components#component-row

**Comment by s-cork** [comment]
Oh wait no you can't

**Comment by s-cork** [comment]
I'm not sure how to do the `rowFormatter` off the top of my head.
It would work well enough for a tabulator in code but more challenging for a tabulator in the designer since you'd need to define it before the init method was executed.

I could raise an event potentially instead

```
def row_formatter(self, row, **event_args):
    # do something with the row
```

**Comment by s-cork** [comment]
That's done.

**Comment by mjmare** [comment]
How would that work with the event?

**Comment by mjmare** [comment]
Oh I see. The event is exposed in the IDE. And the row is the javascript object.

Did you change the example project as well, perhaps?

**Comment by mjmare** [comment]
The cellFormatter works very well. Actually better than returning a DIV with the default formatter. Now the whole cell is colored, as I intended. Great!

```
    def status_formatter(cell, formatterParams, onRendered):
      COLORS = {'IN': ('white', 'green'), 'UIT': ('white', 'red'), 'THUIS': ('black', 'orange')}
      status = cell.getValue()
      color = COLORS.get(status, ('black', 'lightgray'))
      style = cell.getElement().style
      style.color = color[0]
      style.backgroundColor = color[1]
      style.fontWeight = 'bold'
      return status
  
    columns = [
      {'title':"Status", 
       'field':"status", 
       'cellFormatter': status_formatter,
       'hozAlign': 'center',
        'width': 100,},

   }
```
