### ISSUE TITLE
datetime not correctly formatted

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#11]
A column with python datetime values is displayed as [object Object] even when the column formatter is set to "date time".

It probably is a python/javascipt incompatibility and I could probably work around it by converting to strings. OTOH it would be convenient if Tabulator could handle this.

**Comment by s-cork** [comment]
I've got the example tabulator working

I guess it'd be also nice to support the sorter with date and datetime objects too...

**Comment by s-cork** [comment]
closed via 7dfdc770dd7ba9dc5662bc07c2a5e3c7431ba171
Let me know if it works for you!

**Comment by mjmare** [comment]
Works! Excellent. Do you ever sleep?

I noticed that the headerFilter=True (which I use for most columns) does not work for a datetime column. This does not seem to be a limitation of Tabulator (see http://www.tabulator.info/examples/4.9#filter-header)

**Comment by s-cork** [comment]
well spotted - I didn't implement that
for each datetime column interaction I need to override Tabulator's default implementation and clean the datetime object to be a string!
Will update that and let you know when it's done

**Comment by mjmare** [comment]
OK, thx

**Comment by s-cork** [comment]
I've looked more into the filters - and it's not possible to override this one.
The examples on the Tabulator docs aren't actually datetime formatters they're just plain string formatters.
So there's no hook into it. 

You'll have to write your own headerFilterFunction using the examples from the Tabulator docs.
http://tabulator.info/docs/4.9/filter#header

```python
def customHeaderFilter(headerValue, rowValue, rowData, filterParams):
    # headerValue - the value of the header filter element
    # rowValue - the value of the column in this row
    # rowData - the data for the row being filtered
    # filterParams - params object passed to the headerFilterFuncParams property
    dob = rowValue.strftime(filterParams["format"])
    return dob.startswith(headerValue)

#column definition object in table constructor
{'title':"DOB", 
 'field':"dob", 
 'headerFilter':"input", 
 'headerFilterPlaceholder':"dob", 
 'headerFilterFunc': customHeaderFilter, 
 'headerFilterFuncParams': {'format':"%y-%m-%d"}
}
```
Or something...

**Comment by mjmare** [comment]
No biggie. Thanks for investigating.
