### ISSUE TITLE
Progressive Load - Jumps to top of table

### ISSUE THREAD

**Issue by NicoN13** [s-cork/Tabulator#113]
Hi @s-cork 

I noticed today for the first time that when progressive load is set to "scroll" in the tabulator options, it loads the additional rows as I scroll but also jumps to the very top of the table each time new rows are loaded. It doesn't keep the scroll position like before.

TABULATOR_OPTIONS = {
  "maxHeight": 500,
  "pagination": False,
  "progressive_load": "scroll", # load data into the table as the user scrolls
  "progressive_load_scroll_margin": 500,  
  "css_class":["table-striped", "table-bordered"],
  "loading_indicator": False,
}

I've tested all the options and it seems like using maxHeight is causing the issue. If I change the options to only use "height":500 then scrolling works as expected, but using maxHeight causes this jumping to occur while scrolling.

**Comment by s-cork** [comment]
Is there a problem with just setting height?
Consider adding a class to your table that does the max height instead of the max height option.
Otherwise a clone link so I can play would be most useful

**Comment by NicoN13** [comment]
So setting height works fine if I always want a table to be a specific height. However, in some cases I want the table to reduce in height when there are few rows to display. For this I need maxHeight to work.

Here is a clone link to a dummy app displaying the issue:
https://anvil.works/build#clone:DORLRE6RSAIRVIBA=XZGU6HBO2IPG2HM4DSUZCVAC|TGQCF3WT6FVL2EM2=

I have added both height and maxHeight to the tabulator options. Just comment/uncomment the ones you want to see.

**Comment by s-cork** [comment]
@NicoN13 looks like it's a problem with Tabulator itself rather than anvil wrapper

https://github.com/olifolkerd/tabulator/issues/4171

So there's not much I can do.
I've subscribed to the issue so if that gets fixed I'll bump the version as needed.
