### ISSUE TITLE
Horizontal scroll lost on headerSort - V5.3 fix

### ISSUE THREAD

**Issue by NicoN13** [s-cork/Tabulator#116]
Hi @s-cork,

I found that in V5.2 of tabulator, when using headerSort, you lose your scroll position. It always resets to the far left once you've triggered a sort through clicking on the column header.

I know this has been fixed in V5.3+. How much effort would it be to update this so that it works with the current version of tabulator?

See discussions below:
https://github.com/olifolkerd/tabulator/issues/3690
https://github.com/olifolkerd/tabulator/issues/4161

Appreciate that this may not be just a 'quick fix', but just thought to mention.

Regards,

**Comment by s-cork** [comment]
bumped to 5.4.4 which is when that issues was fixed

**Comment by NicoN13** [comment]
I did a reload of the IDE and my app but still same result. I am using the app_table option if that makes any difference.

Do you need a demo app to show this issue?

**Comment by s-cork** [comment]
Yes please. Shouldn't make a difference.

**Comment by NicoN13** [comment]
Here's a clone link:
https://anvil.works/build#clone:JZSLUGAKULFUOFUC=GE7CZWPJGGWF6QIGAKNWXI3I|undefined=

To replicate, scroll to the far right, then sort on that header. You'll notice it sorts and then scrolls all the way to the left of the table.

**Comment by s-cork** [comment]
try now
just pushed a fix

**Comment by NicoN13** [comment]
Still experiencing the same. Do we need to use the development dependency?

**Comment by s-cork** [comment]
Yeah. I'll bump the version once you've confirmed it's fixed on the development branch.

**Comment by NicoN13** [comment]
Works perfectly on the dev branch. Thanks!
