### ISSUE TITLE
Add LayoutModule to Tabulator in Anvil problematic

### ISSUE THREAD

**Issue by NerdNL** [s-cork/Tabulator#120]
Hello Stu,

I tried Tabulator.modules.add("Layout") and also Tabulator.modules.add("LayoutModule") to add this module to the Anvil Tabulator. But I got an error in both cases: "LookupError: LayoutModule".  
Adding the "TooltipModule" in the same manner worked fine.

I need the LayoutModule to use "fitColumns", like so:

      self.tabulator.columns.append({"title": title, "field": field, "layout": "fitColumns", "hoz_align": "left", "headerTooltip": True })

Thanks,
Ad

**Comment by s-cork** [comment]
I'm pretty sure that the layout module is included by default. It's a required module and cannot be removed.

**Comment by s-cork** [comment]
I don't think layout is a column option. I think it's a global option and should be set by tabulator.options or using the designer properties.

**Comment by NerdNL** [comment]
Yes, it is a required module, therefore I was suprised by a look-up error. But I moved it to the tabulator.options as you suggested and warning is gone.
Thanks!
