### ISSUE TITLE
Add row position argument is not working

### ISSUE THREAD

**Issue by vidz1979** [s-cork/Tabulator#125]
Calling add_row with as position argument does not produce effects. Data is always added in the last row.

```python
tabulator.add_row(data, False, 2)
```

**Comment by s-cork** [comment]
It's not index in the sense of third row. It's the row who has an index of 3. It depends what you are using as the index column. If you're using the id column then it will try to find the row whose id column has a value 3. 

If you need more, I'll need more too. A clone link that demonstrates your issue will help. 

Here are the docs for other possible values for index:

https://tabulator.info/docs/5.5/components#lookup

**Comment by vidz1979** [comment]
Thank you! Setted index column and now works.
