### ISSUE TITLE
Missing themes.

### ISSUE THREAD

**Issue by telemix** [s-cork/Tabulator#128]
**Describe the bug**
Not all of the themes described [here](https://github.com/s-cork/Tabulator#themes) exist. The missing ones are : 

bootstrap4
materialize

**To Reproduce**
Add them as per the docs :

```
from tabulator.Tabulator import Tabulator
Tabulator.theme = "bootstrap4"
```

And you see the error : 

```
ERROR: Failed to load theme bootstrap4
```

**Comment by s-cork** [comment]
Hi - please confirm the version of tabulator you are using

These were added in #108
which was live in v2.2.11

I double checked and works for me as expected

**Comment by telemix** [comment]
Ahh, I see. I wasn't paying attention when I selected the version for the dependency. I lazily assumed the drop down in Anvil was in order (most recent at the top), but it's not. Might create a feature request in Anvil to make the dependency list properly order itself.

Closing as no fault.
