### ISSUE TITLE
Custom Sorters

### ISSUE THREAD

**Issue by s-cork** [s-cork/Tabulator#2]
While we're at it do you think you can come up with [custom sorters](http://tabulator.info/docs/4.0/sort#func-custom) too?

> # Custom Sorters
> for advanced sorting can define a custom sorter function in the sorter option:
> ```js
> {title:"Name", field:"name", sorter:function(a, b, aRow, bRow, column, dir, sorterParams){
>         //a, b - the two values being compared
>         //aRow, bRow - the row components for the values being compared (useful if you need to access additional fields in the row data for the sort)
>         //column - the column component for the column being sorted
>         //dir - the direction of the sort ("asc" or "desc")
>         //sorterParams - sorterParams object from column definition array
> 
>         return a - b; //you must return the difference between the two values
>     },
> }
> ```
> The fifth parameter in this callback is a ColumnComponent for the column being sorted.

_Originally posted by @Starwort in https://github.com/s-cork/Tabulator/issues/1#issuecomment-667600254_

**Comment by s-cork** [comment]
I think i've implemented this now. 
i've used the call signature `f(a, b, aRow, bRow)` if you provide `sorterParams` in the column setup then you can use `**params`.

I've done a small test in the example Tabulator and it works there. I think the return value should really be an `int/float` so a `timedelta` object as the return value wouldn't work...

**Comment by Starwort** [comment]
Works as intended (as long as `.total_seconds()` is called on the timedelta, which makes sense)
