### ISSUE TITLE
Use custom objects as row items

### ISSUE THREAD

**Issue by theref** [s-cork/Tabulator#23]
Looking at the docs, it seems that `self.tabulator.data` has to be a dictionary so that the contents of the columns can be defined by `field`.

is it possible to pass a list of objects to `self.tabulator.data` and use it's attributes?
One option is to just use the `__dict__` method of the object, but ideally i'd like to use the original object to make editing easier later on.

**Comment by s-cork** [comment]
Ah yes. I've thought about that. 

And thought this might come up. 

Should be relatively straightforward to implement. 

I have a data loader module for getting items from a row. 

I'd change that code from a getiem to a getattr. 

It would just need an api. 

```python
self.tabulator.options = {
    ???
}
```

Maybe take a look at the docs for using an app_table and the api options. 

I'm thinking - Something like 

```python
self.tabulator.options = {
    use_model: True,
    model_getter: "getitem", # or "getattr"
}
```

Thoughts? Not sure what the best way to express this is. 

When you have a callback there could be a `get_model()` available on tabulator rows and cells. 

```python
def row_click(self, row, **e):
    model = row.get_model()
```
