### ISSUE TITLE
Options and themes not available in v1.0

### ISSUE THREAD

**Issue by theref** [s-cork/Tabulator#24]
**Describe the bug**
`self.tabulator.options` doesn't exist in v1.0

If i switch to v2.* or Development, `options` becomes available, however all my data disappears, so I'm guessing there's an API change from v1 to v2.

Setting the theme via
```
from Tabulator.Tabulator import Tabulator

Tabulator.theme = "simple"
```
has no effect in v1.0 either.

Also, switching between the difference version changes the name of the package (`tabulator` or `Tabulator`) not sure if that is deliberate or not, just wanted to make you aware.

Setting

**Comment by s-cork** [comment]
Yeah v1 and v2 are different. 
Development points to v2

Production points to v1. 
This will change soon. 

See the changelog which documents the differences.
