### ISSUE TITLE
Custom filter

### ISSUE THREAD

**Issue by Starwort** [s-cork/Tabulator#3]
This is the third function-related issue/feature request I've made now :P

According to [this comment by the author of Tabulator](https://github.com/olifolkerd/tabulator/issues/185#issuecomment-281516289), a predicate function can be used to filter data like so:
```js
//define custom filter
function customFilter(data){
    //data - the data for the row being filtered
    // returns a boolean
}
// (...)
$("#example-table").tabulator("setFilter", customFilter);
```

However, I cannot get this to work (and I suspect the same tricks you used for #1 and #2 will be needed here)

My current code (using a factory to make a filter; I tried using multiple filters but date filtering didn't seem to work properly):
```py
        self.tabulator.set_filter(self.make_filter())
        
    def make_filter(self):
        def filter(data):
            name_filter = self.search_name.text or ''
            date_filter = self.search_expires.date
            return name_filter in data['name'] and ((not date_filter) or data['expires'] < date_filter)
        return filter
```
Current behaviour:
<details><summary>Filter Error - No such filter type found, ignoring: <code>null</code></summary>
<pre>
E.findFilter @ tabulator.min.js:8
(anonymous) @ tabulator.min.js:8
E.addFilter @ tabulator.min.js:8
E.setFilter @ tabulator.min.js:8
u.setFilter @ tabulator.min.js:5
set_filter @ (index):1281
(anonymous) @ PyDefUtils.js:1570
f @ rsvp.es.js:320
w @ rsvp.es.js:492
(anonymous) @ rsvp.es.js:556
ce @ rsvp.es.js:2432
characterData (async)
(anonymous) @ rsvp.es.js:2409
le @ rsvp.es.js:2366
x @ rsvp.es.js:555
e.finally @ rsvp.es.js:1106
(anonymous) @ DatePicker.js:159
dispatch @ jquery.min.js?buildTime=1598345055:2
v.handle @ jquery.min.js?buildTime=1598345055:2
trigger @ jquery.min.js?buildTime=1598345055:2
(anonymous) @ jquery.min.js?buildTime=1598345055:2
each @ jquery.min.js?buildTime=1598345055:2
each @ jquery.min.js?buildTime=1598345055:2
trigger @ jquery.min.js?buildTime=1598345055:2
clickApply @ daterangepicker.js?buildTime=1598345055:1407
clickDate @ daterangepicker.js?buildTime=1598345055:1363
i @ jquery.min.js?buildTime=1598345055:2
dispatch @ jquery.min.js?buildTime=1598345055:2
v.handle @ jquery.min.js?buildTime=1598345055:2
</pre>
</details>

**Comment by s-cork** [comment]
Yeah. Anytime you send a python function to JavaScript there’s not natural
way to convert it so you have to check it’s type and then use some skulpt
architecture to covert it.

Won’t be able to do this till next week.

**Comment by Starwort** [comment]
> Yeah. Anytime you send a python function to JavaScript there’s not natural way to convert it so you have to check it's type and then use some skulpt architecture to covert it.

Oof, that sounds painful; at least it should be easier with repetition, right :P

In all seriousness, thanks for putting up with this and hopefully it makes the experience better for everyone else too :)

> Won’t be able to do this till next week.

Totally fair, it's not super urgent anyway - Have a nice week!

**Comment by s-cork** [comment]
done with commit 3e872ab4b3e
