### ISSUE TITLE
AttributeError when running clone of Example

### ISSUE THREAD

**Issue by akrishnamo** [s-cork/Tabulator#34]
**Describe the bug**
When I clone and run the example app from my anvil login, it throws the following error

_**AttributeError: The following column option(s) are invalid: 'align'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:253**_

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):

1. clone the example app
2. run
3. The app seems to run well, but now only the first row of the date of birth column can be editted. Otherwise, sort etc. seem to work fine

The following error messages get printed in the app console. 
get_list_data(n=100) called
get_list_data took: 0.9999 sec
AttributeError: The following column option(s) are invalid: 'align'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:253
AttributeError: The following column option(s) are invalid: 'align'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:253
row_selection_changed: 0 row(s) selected
row_selection_changed: 0 row(s) selected

**Comment by s-cork** [comment]
Thanks for reporting. You can just remove those from the clone within the column definitions. 

That was me testing the api originally to make sure those errors got reported in the console. Particularly for those transitioning form 1.0 to 2.0. Some options that used to be valid now have no affect. `align` being one of them.

**Comment by s-cork** [comment]
You can reclone now - those errors won't be there anymore
