### ISSUE TITLE
Implement deselectRow/selection clearing

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#4]
Let me first thank you for this excellent Anvil component! I'm finding it extremely useful.

I have a small request: could you implement a way to clear the row selection?

I tried self.tabulator._table.deselectRow(...) but it did not work.

Oh it seems that tabulator.select_row() does not work... I tried to pass the row item or the row id, but neither worked. 

TIA
Marcel

**Comment by s-cork** [comment]
i've had a look and have checked `select_row` works fine for me on the example app.

```python
self.tabulator.select_row(0) # single id
self.tabulator.select_row([0,1,2,3]) # list of ids
self.tabulator.select_row('visible')
```

I've added the `deselect_row` function in commit 3887ec079ac3c739840e614fb62a956340dcc8fb which should do the expected and also works on the example app.

```python
self.tabulator.select_row(0) # single id
self.tabulator.deselect_row([0,1,2,3]) # list of ids
self.tabulator.deselect_row() # all currently selected rows
```

let me know if you still have problems.

**Comment by mjmare** [comment]
Ah, thanks to your pointer, I found the problem: I had not set the index to the field being used. And now I also have the confirmation that the key and not some row index should be used. 

It would be useful to have a cheatsheet with Tabulator's usage on the GH page. It is cumbersome to consult the demo app just to check the usage, with Anvil IDE being able to open one page at the time. 

Now I have to find out how to merge these changes on GH into my current Tabulator component (silly Anvil dependencies).

**Comment by s-cork** [comment]
yes - documenting this is something I never got round to but definitely should.
As a minimum i should add better docstrings since anvil now supports autocomplete for depenencies

Very open to pull requests 😉
