### ISSUE TITLE
Clicking on trash icon in the rows triggers two separate deletion for the same row

### ISSUE THREAD

**Issue by arpika99** [s-cork/Tabulator#44]
**Bug description**
If you click on the trash bin icon on one of the rows the `do_delete` function will be called twice. In the 

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Go to the tabulator live app.
2. Click on a trash bin icon on any row.
3. Confirm the row deletion. (The delete function here is called the 1st time)
4. Confirm the row deletion once again. (The delete function here is called the 2nd time)
5. See error. The 2nd delete function will throw an error, because the row does not exist anymore in the data.

**Expected behavior**
After clicking on the trash bin icon, only one confirm panel should come up and delete the row.

**Screenshots**

**Additional context**
This is a small issue, which can be solved by simply removing 2 lines from `tabulator_cell_click` function.
```
def tabulator_cell_click(self, cell, **event_args):
"""This method is called when a cell is clicked - event_args include field and row"""
        field = cell.get_field()
        data = cell.get_data()
        if field == "name":
            Notification(data["name"]).show()
        if field == "delete":  # row to remove
            self.do_delete(data) # row to remove
        print("cell clicked")
```

Since this delete behavior is already handled right here:

```
def delete_link_formatter(cell):
       l = Link(icon="fa:trash", foreground="#ea0a8e", spacing_above="none", spacing_below="None")

       def delete_click(**event_args):
           data = cell.get_data()
           self.do_delete(data)

       l.set_event_handler("click", delete_click)
       l.tag.cell = cell
       return l
```

**I am considering making a PR for this issue**
No

**Comment by s-cork** [comment]
thanks - fixed
there was previously an internal stop propagation that prevented both from triggering.
