### ISSUE TITLE
self.item in custom editors is empty

### ISSUE THREAD

**Issue by jshaffstall** [s-cork/Tabulator#50]
**Describe the bug**

With custom editors, `self.item` ends up as an empty dictionary.  

**To Reproduce**

This can be seen in the example app: https://anvil.works/forum/t/tabulator-v2-release/12046  The favorite color editor doesn't prepopulate with the current value.

Happens from 2.14 onward

**Comment by s-cork** [comment]
Did you try 2.1.5? I tried it on that version and seemed to be fixed.

**Comment by jshaffstall** [comment]
Yes, 2.1.5 works now.  Thanks!
