### ISSUE TITLE
When using a model, add_row doesn't populate row fields

### ISSUE THREAD

**Issue by jshaffstall** [s-cork/Tabulator#51]
**Describe the bug**

Using a model works fine when setting `self.tabulator.data`, but not when calling `self.tabulator.add_row`.  

**To Reproduce**

This app is a modified version of the Tabulator example: https://anvil.works/build#clone:57OSEZIF52F47MED=EJIMR6LNBWQQ6DF5FZFB6MIC

It uses a model object instead of dicts (the model object is solely to test some ideas).  When run initially, the model object is queried and the row fields populated.  

Clicking the Add Row button generates a model instance in the same way, but calls `add_row` to add it to the tabulator.  The fields are not populated initially, but if you click into them (e.g. the favorite color editor) the right value shows.

**Expected behavior**

I'd expect `add_row` with model objects to work the same way that setting `self.tabulator.data` does, populating the row fields with the values from the model object.

**Comment by s-cork** [comment]
@jshaffstall - if you could check the development branch - it should work now.
I'll leave this on Dev for a bit before pushing to published... I imagine you might find a few more issues while you're hacking away.

**Comment by jshaffstall** [comment]
Can confirm this works on development, both in the test app and the real one.  Will let you know if I run into anything else.
