### ISSUE TITLE
add_row after set_sort has strange effects

### ISSUE THREAD

**Issue by jshaffstall** [s-cork/Tabulator#54]
I don't know if this is a bug, or if I'm just not approaching what I want to do the right way.  I want the user pressing Enter in a field to add a new row to the bottom of the table, and to start editing the first field in that row.  

I do that by using a Javascript keydown event to listen for the Enter key.  In that event, I do:

```
    if e.key == 'Enter':
      next_row = self.last_edited_row.getNextRow()
      
      self.tabulator_1.set_sort("date", "asc")
      
      if not next_row:
        next_row = self.add_new_row()

      cells = next_row.getCells()
      cells[0].edit()
```

The idea is to grab the next row of the last edited row, and then to sort in case they entered a date that was before some of the other dates in the table.  If the last edited row was at the end of the table, I add a new row, otherwise put the editing focus on the existing row.

That all works fine as long as the dates consistently increase.  As soon as I put in a date that's earlier than some of the existing dates, the table sorts correctly but the newly added row is put into its sort order instead of at the bottom of the table.

This feels like a Javascript promise delay.  My initial thought had been that the sort wasn't completing right away, but I tried putting a `time.sleep(1)` in there and that didn't change anything.

Here's a clone that exhibits the behavior: https://anvil.works/build#clone:TMXFO5RQIVDB62QQ=ZIJGA2YQSTYP737PQMENHPOS

To replicate it:

1. enter a table row with today's date
2. press enter in the description field
3. enter a row with an earlier date
4. press enter in the description field

The newly added row will end up somewhere other than the end of the table.

**Comment by s-cork** [comment]
Yeah. The issue isn't something I can handle. You're basically directly calling the underlying tabulator methods and the wrapper isn't doing anything to influence the behaviour you're seeing.  

It seems when there's a sort on the rows adding a new row with a value will put it in the sorted position. 

I see there's a bug with the date formatter/editor/sorter when using a None value.

**Comment by jshaffstall** [comment]
This is from 2021, but suggests that tabulator isn't designed to sort after addRow: https://stackoverflow.com/a/64847172  

This one suggests that sorting first and adding a new row also shouldn't see the new row sorted (they use a timeout to delay the sort until after the new row is added): https://stackoverflow.com/a/63629516

Not sure if that's changed for version 5 or not, but that's why I was puzzled at the behavior I was seeing.  I can't find any reference that says that adding a new row after sorting should affect the sort order of the new row.  But that's definitely what's happening.

I found a version 4 jsfiddle and modified it, and can confirm that it didn't happen with version 4 through straight Javascript.  https://jsfiddle.net/b2rfg3zq/  The sort only affects new rows if it's done after the rows are added, not before.

I'm not having any luck creating a version 5 jsfiddle that can sort (my Javascript experience is all pre-import/browser based), so I can't verify how it behaves in that one with plain Javascript.

**Comment by s-cork** [comment]
I can confirm the behaviour is different in Tabulator 5:
https://jsfiddle.net/sc549/d9k1p02w/

**Comment by jshaffstall** [comment]
Thanks for that!  That's unfortunate.  I'll have to see if there's a way to override that behavior.  You'd think there'd be a setting allowing that to be adjusted, since it's a pretty major change in behavior.

**Comment by s-cork** [comment]
if you add this to the date column definition

```python
[
    ..., "sorterParams": {"alignEmptyValues" :"bottom"}},
]

```

Then adding a new row with no values will add it to the bottom of the current page
I've also fixed the date being a None value upsetting the sorter

**Comment by jshaffstall** [comment]
Nice!  That, combined with adding a new row and then changing the date immediately:

```
    row = self.tabulator_1.add_row({})
    row.getCell('date').setValue(self.last_edited_date)
```

Gives me the same behavior I'd have gotten with version 4 tabulator.  Luckily version 5 doesn't auto-sort on every change.  

Thanks for the help!
