### ISSUE TITLE
Unable to access rowFormatter

### ISSUE THREAD

**Issue by akrishnamo** [s-cork/Tabulator#58]
I am trying to setup a table with a rowFormatter, where colorEditable is a function

this is the column definition

`{"title": col, "field": col, "editor": True, 'headerSort': False, 'frozen': TF,'editable':edit_check, 'rowFormatter': colorEditable }`

When I include the 'rowFormatter' key in the dictionary, i get the following error in Anvil
```
AttributeError: The following column option(s) are invalid: 'rowFormatter'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:312
```

**Comment by akrishnamo** [comment]
I guess this is accessible from the design view. Closing this.

**Comment by s-cork** [comment]
rowFormatters can only be defined as a table option not as part of the column definition. 

And yes there is also a custom event to handle the same thing.
