### ISSUE TITLE
Unexpected error: AttributeError: The following column option(s) are invalid

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#63]
I have some code that has not been changed in a while that is "suddenly" giving me warnings. 
It might be due to a newer version of Tabulator, because I failed to pin the version number. Currently I'm using 2.1.5.

The code fetches data and configures the tabulator. When starting up  this works fine. The date time display is correct. 
```
def fetch_data(self):
    items = anvil.server.call('get_files')
    
    def link_formatter(cell, **params):
      data = cell.get_data()
      l = Link(icon="fa:link", foreground="gray", spacing_above="none", spacing_below="None")
      return l

    columns = [
      row_selection_column,
      {'title': 'Naam', 'field':'name', 'sorter': 'string', 'headerFilter': False}, 
      {'title': 'Gewijzigd', 'field':'updated', 'sorter': 'datetime', 
       "formatter": "datetime",
       # "formatter_params": {"format": "iso", "tz": None},
       "formatter_params": {"format": "%Y-%m-%d %H:%M:%S"},
       'headerFilter': False}, 
      {'title': 'Omschrijving', 'field':'description', 'sorter': 'string', 'headerFilter': False}, 
      {'title': 'Tags', 'field':'tags', 'sorter': 'string', 'headerFilter': False}, 
      {"title":"Link", "field":"link", "formatter": link_formatter, 'width': 50, 'headerFilter': False},
    ]      
    self.tabulator.columns = columns
    self.tabulator.data = items
```

When I call this method again (as to refresh the table), I get these errors. The table mostly works but the date time display reverts to "mm/dd/yy" format, which is not correct. 
```
AttributeError: The following column option(s) are invalid: 'title_formatter', 'title_formatter_params', 'hoz_align', 'header_hoz_align', 'header_sort', 'cell_click'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:312
AttributeError: The following column option(s) are invalid: 'formatter_params'. You may need to include the required Module in Tabulator.modules.
at app/tabulator/Tabulator/_custom_modules.py:312
```

I really don't understand what's going on here. Pointers welcome.

**Comment by s-cork** [comment]
Could you provide a clone link that demonstrates the issue? Much easier to help from there.

No changes have been made to tabulator recently.

**Comment by mjmare** [comment]
Can I send a clone link privately?

**Comment by s-cork** [comment]
Yeah - can do it on the forum, as well as reproduction steps. Best if the clone only demonstrates the issue.

**Comment by mjmare** [comment]
On Github discussions you mean? Or the Anvil Forum?

(I apologise BTW, at least one of the issues I raised today would be better posted on the discussions page.)

**Comment by s-cork** [comment]
I meant the anvil forum.

**Comment by mjmare** [comment]
I sanitised the app. Here it is: https://anvil.works/build#clone:CJGOIHMHEUO777UJ=R2KGXCC6PCA4HNIN4QDAFY6R|C6ZZPAPN4YYF5NVJ=|TGQCF3WT6FVL2EM2=

**Comment by s-cork** [comment]
thanks looks like there was a bug with snake case options - should now be fixed on the development branch

**Comment by mjmare** [comment]
Thanks for the quick help. Works fine now.
