### ISSUE TITLE
Buglet in demo app: click on icon does not trigger Cell clicked event

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#8]
I noticed that when one clicks _on_ the bin icon in the demo app nothing happens. When clicking just below the icon the event handler is called. 

Question: why is the formatter 'link' for the first column and Link for the next to last field?

TIA

**Comment by s-cork** [comment]
I think this is new behaviour and a recent bug introduced possible from anvil. Thanks for flagging. Will investigate.

**Comment by s-cork** [comment]
just checked and this bug was introduced by a recent anvil change so i'll look to get that fixed soon. Will close this issue when that happens

**Comment by s-cork** [comment]
changed the example to use a Label instead of a Link.
The underlying bug should go live in the next couple of weeks. But the example is fixed so closing this report. 

And to answer the original question.
No particular reason - it's just to show different examples of what's available.

**Comment by mjmare** [comment]
OK, thank you!
