### ISSUE TITLE
Question:  How do mutators work with Anvil-Tabulator

### ISSUE THREAD

**Issue by mcmasty** [s-cork/Tabulator#81]
Trying to use Mutator as follows:

In Anvil Client Code 
```
Tabulator.modules.add("MutatorModule")

def date_mutator(value, data, type, params, component):
  logger.debug("ENTERING: date_mutator")
  print(value)
  print(data)
  print(type)
  print(params)
  print(component)
  dt_val = datetime.strptime(value, "%Y-%m-%d").date()
  print("HERE")
  print(value)
  print(dt_val)
  value = dt_val
  logger.debug(f"RETURN: {dt_val!r}")
  print("goodby")
  return dt_val
```

```

    self.tabulator_clients.columns = [
      {"title": "Name", "field": "name", "formatter": "text"},
      {"title": "Max Budget", "field": "max_budget", "formatter": "money",
      "formatterParams": {"symbol": "$", "precision": 0}},
      {"title": "Start Date", "field": "start_date", "formatter": "datetime",
      "mutator": date_mutator, "accessor":date_accessor , "formatter_params": {"format": "%Y-%m-%d"}},
...
``` 

sample data ...
```
[{'name': 'Webb', 'max_budget': 420, 'active': True, 'start_date': '2022-11-23', 'end_date': None, 'id': 'ac7d4d5a-7b94-402f-b1b2-e808da66d050', 'created': '2022-11-28T19:29:43.558745', 'modified': '2022-11-28T19:29:43.558745'}, {'name': 'Avida Apartments', 'max_budget': 361.67, 'active': True, 'start_date': '2022-12-01', 'end_date': None, 'id': '3e9ebdec-bed8-45c2-a9a9-1abb96761a97', 'created': '2022-11-28T19:29:43.558745', 'modified': '2022-11-28T19:29:43.558745'}, ...]
```

Output is

```
rapg|clients|DEBUG: 2022-11-29 13:39:58: ENTERING: date_mutator
2022-12-01
proxyobject({'name': 'Avida Apartments', 'max_budget': 361.67, 'active': True, 'start_date': '2022-12-01', 'end_date': None, 'id': '3e9ebdec-bed8-45c2-a9a9-1abb96761a97', 'created': '2022-11-28T19:29:43.558745', 'modified': '2022-11-28T19:29:43.558745'})
data
proxyobject({})
<ColumnComponent proxyobject>
HERE
2022-08-01
2022-08-01
rapg|clients|DEBUG: 2022-11-29 13:39:58: RETURN: datetime.date(2022, 8, 1)
goodby
``` 

So it seems like the mutator is executing, however I am getting the following error ...  
```
TypeError: A datetime formatter expects a datetime object
at app/tabulator/Tabulator/_datetime_overrides.py:22
```  

which seems like the return value of mutator is not making it to cellValue. i.e. the data object returned from mutator is not being accessed by datetime_overrides.py.

Any thoughts on what I might be doing wrong appreciated.

**Comment by s-cork** [comment]
Did you see I posted about your original question on the forum. Might want to check out that post first which might solve what you're trying to do.

**Comment by s-cork** [comment]
If you want to go down the mutator route here:
It looks like your mutator is trying to set a datetime column to a date object
(I've adjusted the error message to be more informative)
in the Anvil Tabulator there is `"date"` and `"datetime"` options, which are different

You're column definition should probably be
`formatter: "date"`

But I would also suggest looking at the `"luxon_datetime"` option - see the forum post for details

**Comment by mcmasty** [comment]
Thanks.

Yeah, I was trying to get mutator to work, since I was thinking about inline editing, and thought the mutator approach would get me there (as you highlighted Tabulator JS does not come with an editor.) 

 
When I try the `date` formatter, it displays as blank on the page.

```      {"title": "Start Date", "field": "start_date", "formatter": "date",
      "mutator": date_mutator, "formatter_params": {"format": "%Y-%m-%d"}},
```

<img width="1335" alt="Screenshot 2022-11-29 at 22 40 03" src="https://user-images.githubusercontent.com/6108038/204702243-c2d070c1-9bf4-47f6-991b-7becf930bb08.png">


I keep hitting different combinations of stumbling blocks ....

From my understanding / quick recap:
-> Challenge with date/datetime overrides is they don't play nice with dates as strings  
-> Challenge with mutators is they don't seem to play nice with date/datetime overrides
-> Challenge with JS (tabulatorjs & luxonjs)  is there is no date editor 

Can we take a step back?  I think it might be a quicker resolution.

Do you have an opinion on my original question: How do you recommend handling fields which contain dates as strings?

I have a list of dicts sourced from an API, the date fields are strings.

I want to have inline editing of date fields in Tabulator, similar to your demo app.

I want to avoid pre-processing, that is iterating the entire list converting the strings to a date object before setting tabulator data to the list.  

I'd like to stay as close to out-of-the-box functionality as I can.

**Comment by s-cork** [comment]
I'd probably do the luxon thing and then use a custom editor
the source code for the other one is in the repository but it is basically

```python
from anvil.js import get_dom_node

def date_editor(cell , **editor_params):

    dt = date.fromisoformat(cell.get_value()) # adjust for your format
    dp = DatePicker(date=dt, spacing_above="none", spacing_below="none")

    # some styling
    dom_node = get_dom_node(dp)
    inputNode = dom_node.firstElementChild
    inputNode.style.fontSize = "inherit"
    inputNode.style.padding = "0"
    dom_node.style.display = "inline-flex"
    dom_node.style.justifyContent = "space-between"
    dom_node.style.height = "100%"
    dom_node.style.width = "100%"
    inputNode.nextSibling.style.bottom = "6px"

    def change(**event_args):
        dp.raise_event("x-close-editor", value=dp.date.isoformat())
        # adjust for your format

    dp.add_event_handler("change", change)

    def hide(**e):
        dp.date = dp.date  # force the calendar picker to close

    dp.add_event_handler("hide", hide)

    return dp

```

**Comment by s-cork** [comment]
Note also that if your dates are in YYYY-MM-DD format (and that's the format you want to display)
then you can just sort them as strings and don't need luxon at all

**Comment by mcmasty** [comment]
@s-cork 

Thanks so much!!  

I'll try the vanilla/string approach with a custom editor until it doesn't work then I'll fold luxon into the solution.

I apologize for all the back & forth.  I appreciate you and your willingness to help me!

Hopefully I won't have any additional questions :)

**Comment by s-cork** [comment]
no worries - closing for now - feel free to open the issue if something doesn't work for you
