### ISSUE TITLE
Support for tooltips

### ISSUE THREAD

**Issue by mjmare** [s-cork/Tabulator#9]
Hi Stu,

Might be nice to support tooltips.

Got it working manually, but an Anvil event handler would be nicer? TIA

```
    def tooltip(cell):
      row=dict(cell.getData())
      return row['field']

    self.tabulator.columns = [
      {'title':"icon", 'field':"icon", 'formatter':icon_formatter, 
       'tooltip': tooltip,
       'cellHozAlign': 'right', 'width': 50},
      {'title':"text", 'field':"text"},
    ]
```

**Comment by s-cork** [comment]
Sure. Did you fancy making a pull request for the feature?

**Comment by mjmare** [comment]
Sure it works, but it is not as integrated as the other features.

(Hmm, don't know how to do a pull request.... There must be tons of tutorials but never got around doing it. Just an amateur flying solo here)

**Comment by s-cork** [comment]
Have you used a local git workflow with anvil yet?
If not that will be the start.

1. fork this project on github
2. clone your fork onto your local machine
3. create a new blank app called Tabulator in anvil
4. get the git clone link for this new app
5. change the command from `git clone <long link`> to `git remote add anvil <long link>`
6. then force push the local branch to anvil - `git push -f anvil`
7. make your changes in anvil
8. pull your changes locally from anvil
9. push your changes to your github fork
10. make the pr

😅 

Or just post the code snippets that did the integration and I can add them.
Or if that's all too much I can add the integration.

here's the tabulator docs on tooltips http://tabulator.info/docs/4.9/format#tooltips if you haven't seen them.

**Comment by s-cork** [comment]
Just checking in on this - did you want to make a pr or shall I go ahead and add it?

**Comment by mjmare** [comment]
Please go ahead, I won't be able to come round to it.

**Comment by s-cork** [comment]
This issue got lost but looking back it now, I think the original post is actually the preferred option here, since a tooltip can also just be `True`.
