### ISSUE TITLE
Client readable view - fetch only certain columns

### ISSUE THREAD

**Issue by NicoN13** [s-cork/Tabulator#98]
Moving this feature request over from the anvil Forum, but here was the original discussion: [https://anvil.works/forum/t/querying-client-readable-tables/16567?u=neeeco](url)

I'd like to use the app_table option from Tabulator, but only fetch certain columns which I know I'll use. Currently, if we set the app_table option in Tabulator, all the columns are fetched. I don't mind having links to the unused columns, although perhaps that might be beneficial to avoid as well. But ideally, I would like to only fetch columns that I specify in a list, similar to the q.fetch_only(*my_columns) query that we can use with app_tables.my_table.search(q.fetch_only()) in anvil.

**Comment by s-cork** [comment]
there is already a `set_query()` option and you could do `self.tabulator_1.set_query(q.fetch_only(...))`
but that doesn't help with the first load
i've just added an `initial_query` to the available options.

```python
from tabulator.Tabulator import Query


...

    self.tabulator.options = {
        ...
        "initial_query": Query(q.fetch_only(...)),
    }

```

You'll need to switch to the development dependency to try it out

**Comment by s-cork** [comment]
@NicoN13  is that working out for you?

**Comment by NicoN13** [comment]
Hi @s-cork, yes was testing it this morning and seems to be working as expected. I am noticing an improvement in the loading time. Thanks
